pipeline {
    agent any

    stages {

        /* ============================
         🟥 4) Create ArgoCD Application
        ============================= */
        stage('Create ArgoCD Application') {
            steps {
                sh '''
                  set -e

                  export AWS_REGION=us-east-1
                  export CLUSTER_NAME=hello-devops-production-cluster

                  echo "🔹 Updating kubeconfig..."
                  aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

                  echo "🔹 Applying Security ArgoCD Application..."

                  kubectl apply -f - <<EOF
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-tools
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ahmedlebshten/Jenkins-Pipeline-Build-Infra.git
    targetRevision: HEAD
    path: security-tools
  destination:
    server: https://kubernetes.default.svc
    namespace: security-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
EOF

                  echo "🎉 Security Tools ArgoCD Application Created Successfully!"
                '''
            }
        }

    }
}
